### ISSUE TITLE
Incoming query with after hash not parsed

### ISSUE THREAD

**Issue by toastal** [sporto/hop#27]
I'm using what is essentially a callback url from Facebook to get an oauth token that always has `#_=_` appended to it. From what I'm reading, I can't pass in your own hash so I tried doing a `match1 Auth "_=_"` to match it into my routing. That worked-ish in that the routing got it, but the problem is that the URL is structured _properly_ in that it's `http://my.callback.url/?code=stringToken#_=_` and as such `location.query` logs out as `Dict.fromList []`. Obviously I'm trying to get the code query and store it as my auth token, but the query list is empty and can't think of how to maybe unmatch a certain hash. Hop's docs seem to talk about the query string ordering... How do you recommend handling this case?

(Relevant Stack Overflow: https://stackoverflow.com/questions/7131909/facebook-callback-appends-to-return-url )

**Comment by sporto** [comment]
When using hash routing this is a challenge.

I made the decision to have the query string after the hash when using hash routing e.g. `#users/1?k=1`
Mostly because of aesthetics, so the Hop will ignore the real query in this case. Query is meant to go before the hash `?k=1#users/1` but looks ugly for routing.

I can suggest:

- In your urlParser function changed so you send the  `Navigation.Location` record as well, something like:

```
urlParser =
    Navigation.makeParser (\loc ->  (matchUrl routerConfig loc.hash, loc))
```

Then you can store that location record and use it to find the real query string using `location.search`.
See http://package.elm-lang.org/packages/elm-lang/navigation/1.0.0/Navigation#Location

- Or Trying push state routing instead

- Or dealing with auth token in a previous step in the app, for example a page that stores the token and then renders the Elm app, passing the token as a flag.

**Comment by toastal** [comment]
Those are definitely options. If I had a real server setup I could probably rewrite my URLs properly as well. Thanks for that part; I'll look into what would work best for me.

Is there a particular reason why you can't have both? I could see this being a case for other people as well. Say like turn the location.search into a `Dict` and then merging the `Dict` that Hop makes on top of it? ...Or is that generally more confusing/possibly-breaking?

**Comment by sporto** [comment]
It comes down to being able to do a round trip:

If I merge tem
```
?a=1#users/1?b=2

--> [ ... query = Dict.fromList [("a", "1"), ("b", "2")] ]
```

But then when you convert that back to URL you would get:

```
#users/1?a=1&b=2
```

So this would be unexpected. Don't know what the solution is, maybe I need to just use the proper query string and get over that being ugly e.g. `?k=1#users/1`

**Comment by toastal** [comment]
Ha. Well I got it working by manually checking that case. The problem then became that I couldn't remove the query string from the URL (and being an auth token, I definitely need it gone). I think I probably need to switch to the non-hash routing (but obviously I was just following the example).

```elm
urlParser : Parser ( Route, Hop.Types.Location )
urlParser =
    let
        hreffer loc =
            case loc.hash of
                "#_=_" ->
                    [ .origin, .pathname, always "#/auth", .search ]
                        |> List.map (\fn -> fn loc)
                        |> String.join ""

                _ ->
                    loc.href
    in
        makeParser (hreffer >> matchUrl routerConfig)
```

**Comment by toastal** [comment]
The hashing was nice because I didn't have to have anything special setup to reroute everything back on itself for the SPA.

**Comment by toastal** [comment]
I switched to *real* routing instead of hash routing to fix my issue.
