### ISSUE TITLE
"Cannot GET" route error with direct links

### ISSUE THREAD

**Issue by Masaki42** [sporto/hop#30]
Hello, I have a small app with two routes: "/" and "/:id", but they works only if I navigate through links inside my app. If I try to go directly to the "/:id" I get "Cannot GET {{id}}" error.

Routes: https://github.com/kostyaev/image-turk/blob/dev/web/elm-app/src/Routing.elm

elm 0.17.1
macOS 10.11.4

**Comment by pablohirafuji** [comment]
Hey, are you using some server to serve the app files and do the routing? I ask that because the problem may be that without the hash, the browser try to get the file within the respective url if there is no server routing the url to the Elm app. I'm using hop with `hash = True` because I don't know a way around this (actually, there's some [work around](http://stackoverflow.com/questions/16267339/s3-static-website-hosting-route-all-paths-to-index-html) if you intend to host it in aws S3, but it's kind hacky).
Let me know if works with `hash = True` or I don't understood the question.

**Comment by sporto** [comment]
@pablohirafuji 	is right. When not using hash routing you need your server to respond to all the possible routes in your application. e.g. your server needs to recognize `/:id` and serve the Elm application. 

For an example in Express see https://github.com/sporto/hop/blob/master/examples/full/dev_server.js#L24

So here express matches `/app/*` and returns index.html. After that Hop will match the appropiate route.

I'll close this as I don't think there is further action, please repoen if you deem necessary.
